staging:
  auth:
    fingerprint: B8:53:D4:A7:E6:1B:86:FF:4E:91:F6:2D:34:EB:A6:A2:8F:89:9E:6F
    target_url: https://thoughtworks.oktapreview.com/app/thoughtworks_labstwgaragesale_1/k21g8tbrFOLVMVOMTINY/sso/saml
production:
  auth:
    fingerprint: 42:53:40:BF:B7:19:41:BA:A7:6B:10:67:97:C7:8C:B2:49:3A:4D:32
    target_url: https://thoughtworks.okta.com/app/thoughtworks_labstwgaragesale_1/kql19ugdLGCTBGIINZXR/sso/saml